site_name: AppForge Bench Docs
site_url: https://benchmark-project-website.github.io/AppForge-Bench/

theme:
  name: material

nav:
  - ğŸŒ Home: https://benchmark-project-website.github.io/
  - ğŸš€ Get Started: index.md
  - ğŸ“¦ Downloads:
      - "ğŸ§± AppForge.zip": "https://github.com/benchmark-project-website/benchmark-project-website.github.io/releases/download/v1.0.0/AppForge.zip"
      - "ğŸ§© AppForge_Bench.zip": "https://github.com/benchmark-project-website/benchmark-project-website.github.io/releases/download/v1.0.0/AppForge_Bench.zip"
  - ğŸ’¬ FAQ: faq.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
